"use client";

import AppLayout from '@/components/Layout/Layout'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import CartProvider from '@/context/CartContext/CartContext'
import { ApolloWrapper } from '@/apollo/apolloClient'
import EmployeeProvider from '@/context/MeEmployee/EmployeeContext';

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const hanuman = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <ApolloWrapper>
        <body className={hanuman.className} suppressHydrationWarning={true}>
          <EmployeeProvider>
            <CartProvider>
              <AppLayout>{children}</AppLayout>
            </CartProvider>
          </EmployeeProvider>
        </body>
      </ApolloWrapper>
    </html >
  )
}
